import {fields,analyze} from './engine.js';
import {escape as e,sourceLinks,chip} from './html.js';

export function intakeView(draft = {}) {
  return `<div class="page-head"><div><p class="eyebrow">SANDBOX / STRUCTURED TRIAGE</p><h1>Start with the founder.</h1><p class="lede">Keep their request intact. Add the facts you know.<br>Build a brief for the decisions that need human judgment.</p></div><button data-action="reset-intake">Reset draft</button></div><div class="banner">◇ <span>Transparent rules, no AI inference. Your text is preserved; the selections below drive the review prompts.</span></div><div class="section-grid"><section class="panel"><form id="intake-form"><div class="form-grid"><div class="field wide"><label for="founder-prompt">The founder's initial request</label><textarea id="founder-prompt" name="prompt" required minlength="15" maxlength="10000" placeholder="I'm a non-US founder and I want a Delaware company…">${e(draft.prompt || '')}</textarea></div><div class="field wide"><label for="residence">Stated residence country / countries (optional)</label><input id="residence" name="residence" maxlength="150" value="${e(draft.residence || '')}" placeholder="Unknown is a valid starting point"></div>${fields.map(f=>`<div class="field"><label for="${f.id}">${e(f.label)}</label><select id="${f.id}" name="${f.id}">${Object.entries(f.options).map(([v,label])=>`<option value="${v}" ${draft[f.id]===v?'selected':''}>${e(label)}</option>`).join('')}</select></div>`).join('')}</div><p class="form-note">Use fictional information. The residence entry is recorded, not used to infer nationality, tax status, or country-specific law.</p><button class="primary" type="submit">Build review brief →</button></form></section><section id="intake-result" aria-live="polite"><div class="panel"><p class="eyebrow">YOUR REVIEW BRIEF</p><h2>Room for the unknown.</h2><p class="muted">Submit the intake to see missing facts, source-linked concerns, and suggested specialist roles.</p><div class="method-row"><span>01 / Preserve</span><p>Keep the request and stated facts separate.</p></div><div class="method-row"><span>02 / Clarify</span><p>Make unanswered questions visible.</p></div><div class="method-row"><span>03 / Review</span><p>Route decisions to the right specialist.</p></div></div></section></div>`;
}

export function resultView(input,data) {
  const result = analyze(input);
  return `<div class="panel"><div class="section-title"><div><p class="eyebrow">REVIEW BRIEF</p><h2>Questions before structure.</h2></div>${chip('Needs review','specialist')}</div><p class="muted">${e(result.limitations)}</p><h3>Information still needed</h3><ul class="list">${result.missing.map(m=>`<li>${e(m)}</li>`).join('')}<li>All owners' actual tax residency, US travel history, funding transactions, and home-country treatment</li></ul>${result.concerns.map(r=>`<article class="concern"><h3>${e(r.title)}</h3><p>${e(r.detail)}</p>${sourceLinks(r.sourceIds,data.sources)}<p class="muted" style="margin-top:10px">Review with: ${e(r.role)}</p></article>`).join('')}<h3>Baseline checks for every intake</h3>${data.common.baseline.map(r=>`<article class="concern"><h3>${e(r.title)}</h3><p>${e(r.detail)}</p>${sourceLinks(r.sourceIds,data.sources)}</article>`).join('')}<button data-action="export-intake">↓ Export intake JSON</button></div>`;
}
