import {escape as e, chip, sourceLinks} from './html.js';

export function library(data, query = '') {
  const found = data.cases.filter(c => JSON.stringify(c).toLowerCase().includes(query.toLowerCase()));
  return `<div class="page-head"><div><p class="eyebrow">NON-US FOUNDERS / DELAWARE FORMATION</p><h1>Every structure starts<br>with a better question.</h1><p class="lede">Five founder stories. The missing facts, the right questions,<br>and the moments that need specialist judgment.</p></div><button data-action="export-all">↓ Export dataset</button></div>
  <div class="stats"><div class="stat"><b>05</b><span>Representative archetypes<br>Entirely synthetic</span></div><div class="stat"><b>25</b><span>Proposed intake questions<br>With a reason for each</span></div><div class="stat"><b>${data.sources.length}</b><span>Primary source references<br>Checked 26 Sep 2026</span></div></div>
  <div class="banner"><span>◇</span><span><strong>A casebook, built for exploration.</strong> Fictional scenarios with real references. Specialist review is still required.</span></div>
  <div class="toolbar"><h2>The case library <span class="muted">/ ${found.length} cases</span></h2><label><span class="visually-hidden">Search cases</span><input class="search" id="search" type="search" placeholder="Search cases, topics, countries…" value="${e(query)}"></label></div>
  <div class="cards">${found.map(c => `<a class="case-card" href="#case/${c.id}"><div class="card-top"><span class="case-number">CASE / ${c.number}</span>${chip(c.archetype)}</div><h2>${e(c.title)}</h2><p>${e(c.subtitle)}</p><div class="tags">${c.tags.map(t => chip(t)).join('')}</div><div class="card-bottom"><span>${e(c.region)}</span><span aria-hidden="true">Explore ↗</span></div></a>`).join('')}${!found.length ? '<div class="empty">No cases match this search. Try “LLC”, “IP”, or a country.</div>' : `<div class="case-card intro-card"><div class="card-top"><span class="eyebrow" style="color:#c1cebd">FROM CASE TO CONVERSATION</span><span>↗</span></div><h2>What would you<br>ask next?</h2><p>Try a new founder scenario and build a structured review brief.</p><a class="button" href="#intake">Try an intake <span>→</span></a></div>`}</div>
  <div class="footer-line"><span>MANUALLY AUTHORED · NO REAL CLIENT DATA</span><span>Research snapshot / September 2026</span></div>`;
}

export function caseView(c, data, answers = {}) {
  const answered = c.questions.filter(q => answers[q.id]?.trim()).length;
  return `<a class="back" href="#cases">← Back to case library</a><div class="detail-head"><div><p class="eyebrow">CASE ${c.number} / ${e(c.archetype)}</p><h1>${e(c.title)}</h1><p class="lede">${e(c.subtitle)}</p></div><div class="actions"><button data-action="export-case" data-id="${c.id}">↓ JSON</button><button data-action="export-brief" data-id="${c.id}">↓ Review brief</button><button data-action="use-case" data-id="${c.id}">Try this intake ↗</button></div></div>
  <div class="banner" style="margin-top:24px">${chip('Synthetic')}<span>Invented scenario · Questions below are proposed, not a client transcript · Not expert validated</span></div>
  <p class="eyebrow">01 / THE INITIAL PROMPT</p><blockquote class="prompt">“${e(c.prompt)}”</blockquote>
  <div class="section-grid"><section class="panel"><p class="eyebrow">02 / WHAT WE KNOW</p><h2>Initially provided</h2><ul class="list">${c.provided.map(v=>`<li>${e(v)}</li>`).join('')}</ul></section><section class="panel"><p class="eyebrow">03 / WHAT WE NEED</p><h2>Important information missing</h2><ul class="list">${c.missing.map(v=>`<li>${e(v)}</li>`).join('')}</ul></section></div>
  <section class="panel"><div class="section-title"><div><p class="eyebrow">04 / THE NEXT CONVERSATION</p><h2>Questions, with a purpose</h2></div><span class="progress-label" id="progress">${answered} / ${c.questions.length} practice answers</span></div><p class="muted">Optional practice notes stay in this tab until reload. An answer recorded here has not been verified and does not resolve a concern.</p>${c.questions.map((q,i)=>`<div class="question"><label for="answer-${q.id}"><span class="number">${String(i+1).padStart(2,'0')} / </span>${e(q.question)}</label><p class="why"><strong>Why we ask:</strong> ${e(q.why)}</p>${sourceLinks(q.sourceIds,data.sources)}<textarea id="answer-${q.id}" data-case="${c.id}" data-question="${q.id}" maxlength="5000" placeholder="Add a fictional practice answer…">${e(answers[q.id] || '')}</textarea></div>`).join('')}</section>
  <div class="section-grid"><section class="panel"><p class="eyebrow">05 / WHAT MATTERS</p><h2>Relevant concerns</h2>${[...c.concerns,...data.common.baseline].map(r=>`<article class="concern"><h3>${chip(r.level,r.level.toLowerCase())}${e(r.title)}</h3><p>${e(r.detail)}</p>${sourceLinks(r.sourceIds,data.sources)}${r.evidenceGap?`<p class="evidence-gap">Evidence gap: ${e(r.evidenceGap)}</p>`:''}</article>`).join('')}</section><section class="panel"><p class="eyebrow">06 / WHERE JUDGMENT STARTS</p><h2>The specialist handoff</h2>${c.specialists.map(s=>`<article class="handoff"><h3>${e(s.role)}</h3><p>${e(s.decision)}</p><small><strong>Needs:</strong> ${e(s.needs)}</small></article>`).join('')}<p class="notice">This case flags decisions for a qualified adviser. It does not recommend an entity or establish a filing or immigration outcome.</p></section></div><p class="takeaway">${e(c.takeaway)}</p>`;
}

export function sourceView(data) {
  return `<div class="page-head"><div><p class="eyebrow">EVIDENCE / PRIMARY REFERENCES</p><h1>The source register.</h1><p class="lede">A dated research trail, with scope and uncertainty made visible.</p></div></div><div class="banner"><span>◇</span><span>Checked 26 September 2026. Sources may change. “Checked” means consulted for this prototype, not a legal opinion.</span></div><p class="notice">Source conflict: Delaware's LLC payment page and statutory page display different annual-tax amounts. No amount is embedded in the advice or intake rules. Confirm the applicable period and effective law before use.</p><div class="source-grid">${data.sources.map(s=>`<article class="source-card"><div class="source-meta">${chip(s.status,s.status)}<span>${e(s.publisher)} · ${e(s.scope)}</span></div><h2>${e(s.title)}</h2><p>${e(s.summary)}</p><a href="${e(s.url)}" target="_blank" rel="noopener noreferrer">Read primary source ↗</a><p class="muted" style="margin-top:12px;margin-bottom:0">Checked ${e(s.checkedAt)}</p></article>`).join('')}</div>`;
}

export function methodView() {
  return `<div class="prose"><p class="eyebrow">METHOD / BOUNDARIES</p><h1>A small, inspectable PoC.</h1><p class="lede">Explore what good intake looks like before automating professional judgment.</p><div class="panel" style="margin-top:28px"><h2>What this dataset is</h2><p>Five fictional cases manually authored to cover different decisions: ownership, financing, operations, existing IP, and relocation. They are illustrative archetypes, not statistically representative observations.</p><p>No actual client files were supplied or used. These are synthetic cases, not deidentified records. The questions are proposed examples, not claims about conversations that happened.</p><h2>How the intake works</h2><p>The original prompt is preserved. Seven explicit selections trigger deterministic review prompts. The system does not extract facts from your free text, infer tax residency, choose an entity, or make a legal decision. “Not yet known” remains unknown.</p><h2>What the sources establish</h2><p>References support limited US rule summaries. Applying them to a fictional fact pattern is editorial triage. Home-country treatment, contracts, banking acceptance, visas, and state-by-state obligations require additional evidence and professional analysis.</p><h2>Human review is the next step</h2><p>Ask US and relevant home-country specialists to validate the concerns, missing questions, source applicability, and escalation thresholds. Do not use this dataset as validated legal ground truth or as a holdout benchmark for a model trained on the same cases.</p><h2>Data handling</h2><p>No analytics, cloud storage, model calls, or external fonts. Practice answers live in memory only. Exported files include your notes; use fictional information in this prototype. Source links open external government websites.</p></div></div>`;
}
